name: Translate Docs
on:
  workflow_dispatch:

jobs:
  translate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          file: "README.md"
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          deepseek-api-key: ${{ secrets.DEEPSEEK_API_KEY }}
          google-api-key: ${{ secrets.GOOGLE_API_KEY }}
          google-model: ${{ secrets.GOOGLE_GENERATIVE_MODEL }}
          openai-model: ${{ secrets.OPENAI_GENERATIVE_MODEL }}
          ss-model: ${{ secrets.SS_MODEL }}

      - uses: EndBug/add-and-commit@v9
