name: Translate Markdown Files

on:
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run translation script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_GENERATIVE_MODEL: ${{ secrets.GOOGLE_GENERATIVE_MODEL }}
          OPENAI_GENERATIVE_MODEL: ${{ secrets.OPENAI_GENERATIVE_MODEL }}
          SS_MODEL: ${{ secrets.SS_MODEL }}
        run: go run translate.go README.md

      - uses: EndBug/add-and-commit@v9
