name: Translate Markdown
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          cd .github/scripts
          go mod init translator
          go get github.com/cohesion-org/deepseek-go
          go mod tidy
          cd ../../

      - name: Run translation script
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: go run .github/scripts/translate.go .github/scripts/deepseek.go
